In [13]:
import pandas as pd
import random
import numpy as np
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [14]:
path = '/content/drive/MyDrive/EstatisticaUdemy/Arquivos/BasesDeDados/credit_data.csv'

dataset = pd.read_csv(path)
dataset.head()

i#clientid        income        age         loan  c#default
0           1  66155.925095  59.017015  8106.532131          0
1           2  34415.153966  48.117153  6564.745018          0
2           3  57317.170063  63.108049  8020.953296          0
3           4  42709.534201  45.751972  6103.642260          0
4           5  66952.688845  18.584336  8770.099235          1

In [15]:
dataset.dropna(inplace=True)

In [16]:
dataset.describe()

i#clientid        income          age          loan    c#default
count  1997.000000   1997.000000  1997.000000   1997.000000  1997.000000
mean   1001.956935  45333.864334    40.807559   4445.487716     0.141713
std     576.702206  14325.131177    13.624469   3046.792457     0.348842
min       1.000000  20014.489470   -52.423280      1.377630     0.000000
25%     503.000000  32804.904487    28.990415   1936.813257     0.000000
50%    1002.000000  45788.747100    41.317159   3977.287432     0.000000
75%    1501.000000  57787.565659    52.587040   6440.861434     0.000000
max    2000.000000  69995.685578    63.971796  13766.051239     1.000000

In [17]:
X = dataset.iloc[:, 1:4].values
X

array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03],
       [3.44151540e+04, 4.81171531e+01, 6.56474502e+03],
       [5.73171701e+04, 6.31080495e+01, 8.02095330e+03],
       ...,
       [4.43114493e+04, 2.80171669e+01, 5.52278669e+03],
       [4.37560566e+04, 6.39717958e+01, 1.62272260e+03],
       [6.94365796e+04, 5.61526170e+01, 7.37883360e+03]])

In [18]:
y = dataset.iloc[:, 4].values
y

array([0, 0, 0, ..., 1, 0, 0])

In [19]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X = scaler.fit_transform(X)
X

array([[0.9231759 , 0.95743135, 0.58883739],
       [0.28812165, 0.86378597, 0.47682695],
       [0.74633429, 0.99257918, 0.58262011],
       ...,
       [0.48612202, 0.69109837, 0.40112895],
       [0.47500998, 1.        , 0.1177903 ],
       [0.98881367, 0.93282208, 0.53597028]])

In [30]:
from sklearn.feature_selection import VarianceThreshold

variancia = VarianceThreshold(threshold=0.027)
X_novo = variancia.fit_transform(X)

In [31]:
X_novo

array([[0.9231759 , 0.58883739],
       [0.28812165, 0.47682695],
       [0.74633429, 0.58262011],
       ...,
       [0.48612202, 0.40112895],
       [0.47500998, 0.1177903 ],
       [0.98881367, 0.53597028]])

In [24]:
np.var(X[0]), np.var(X[1]), np.var(X[2])

(0.027646353650092187, 0.05741515340722347, 0.028389480276199003)

In [27]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [28]:
naive_sem_selecao = GaussianNB()
naive_sem_selecao.fit(X, y)
previsoes = naive_sem_selecao.predict(X)
accuracy_score(previsoes, y)

0.9253880821231848

In [32]:
naive_com_selecao = GaussianNB()
naive_com_selecao.fit(X_novo, y)
previsoes = naive_com_selecao.predict(X_novo)
accuracy_score(previsoes, y)

0.8472709063595393